transcribe_dna <- function(dna) {
 
  mrna_sequence <- gsub("T", "U", dna)  
  return(mrna_sequence)
}


dna <- "CCTTCTGCCATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACC
CAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGG
GGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAG
CTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCA
TTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAA"


mrna <- transcribe_dna(dna)


print(paste("Original DNA Sequence: ", dna))
print(paste("Transcribed mRNA Sequence: ", mrna))
